### ISSUE TITLE
Compiling example fails

### ISSUE THREAD

**Issue by perpetual-hydrofoil** [philberty/gccpy#1]
Seriously awesome project. Using the example code at http://gcc.gnu.org/wiki/gccpyinstall (with or without commenting out the print statement in foo2.py).

$ cat Makefile
all:
        gccpy -O0 -fdump-tree-gimple -fpy-dump-dot -c foo2.py -o foo2.o
        gccpy -O0 -fdump-tree-gimple -fpy-dump-dot -fpy-gen-main -c foo1.py -o foo1.o
        gccpy -O0 -o test foo1.o foo2.o

clean:
        rm *.o *.gpyx *.gimple *.dot

$ make
gccpy -O0 -fdump-tree-gimple -fpy-dump-dot -c foo2.py -o foo2.o
DEBUG: <../../gccpy/gcc/python/gpy-data-export.cc:36> Trying to write export data to foo2.export.gpyx
gccpy -O0 -fdump-tree-gimple -fpy-dump-dot -fpy-gen-main -c foo1.py -o foo1.o
DEBUG: <../../gccpy/gcc/python/gpy-data-export.cc:73> Trying to lookup module data on foo2
DEBUG: <../../gccpy/gcc/python/gpy-data-export.cc:81> Trying to open <./foo2.export.gpyx>
DEBUG: <../../gccpy/gcc/python/gpy-data-export.cc:36> Trying to write export data to foo1.export.gpyx
gccpy -O0 -o test foo1.o foo2.o
foo2.o:(.bss+0x0): multiple definition of `__MOD_INIT_CHK'
foo1.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make: **\* [all] Error 1

**Comment by perpetual-hydrofoil** [comment]
Forgot to mention, this is using the git branch in the gcc repo as recommended on that page, not the development branch at github.com/redbrain

**Comment by philberty** [comment]
Ah nice find sorry I have a fix for this but I haven't been able to push it because I have no Internet at home meant to be getting it today though thanks for the big report!! :)

**Comment by perpetual-hydrofoil** [comment]
great - no prob and thanks for the fast response!

**Comment by philberty** [comment]
Fixed this now https://github.com/redbrain/gccpy/commit/dd476e8bd3e5227d8264cec0c7055c83f61b785e

**Comment by perpetual-hydrofoil** [comment]
Thanks!
